export { default as LocaleAlternates } from './LocaleAlternates.svelte'
export { default as LanguageManager } from './LanguageManager.svelte'
export { default as LanguageSwitcher } from './LanguageSwitcher.svelte'
export { init } from './init.svelte.js'
export type { Options } from './types/Options.js'
